// lib/services/assessment-to-certificate-mapper.ts
import type { ClinicalAssessment, Patient, Clinic, Certificate, TestResult } from '@/lib/types/database';
import { fitnessDecisionToCertificateType, fitnessDecisionToFitnessStatus } from '@/lib/utils/fitness-mapping';
import { TestResultsService } from './test-results-service';
import { DateFormatter } from '@/lib/utils/date-formatter';

export class AssessmentToCertificateMapper {
  /**
   * Create a certificate draft from a completed assessment
   */
  static createCertificateFromAssessment(
    assessment: ClinicalAssessment,
    patient: Patient,
    clinic: Clinic,
    testResults: TestResult[]
  ): Partial<Certificate> {
    const now = new Date();
    const issueDate = DateFormatter.formatForDatabase(now);

    // Determine certificate type from doctor decision
    const certificateType = fitnessDecisionToCertificateType(assessment.doctor_decision);

    // Convert restrictions array to readable string
    const restrictionsString = assessment.restrictions?.length
      ? assessment.restrictions.join('. ') + '.'
      : undefined;

    // Map referrals to boolean flags
    const referrals = TestResultsService.extractReferrals(testResults, assessment.rules_engine_summary);

    // Generate diagnosis from clinical findings and history
    const diagnosis = this.generateDiagnosis(assessment);

    // Generate recommendations from follow-up and additional notes
    const recommendations = this.generateRecommendations(assessment);

    // Determine medical type (could be derived from appointment type, but we'll keep as is)
    const medicalType = this.determineMedicalType(assessment);

    return {
      clinic_id: clinic.id,
      patient_id: patient.id,
      appointment_id: assessment.appointment_id,
      certificate_number: '', // will be generated by repository
      certificate_type: certificateType,
      issue_date: issueDate,
      exam_date: assessment.started_at ? DateFormatter.formatForDatabase(assessment.started_at) : issueDate,
      valid_from: issueDate,
      valid_until: DateFormatter.addDays(issueDate, 365), // default 1 year
      diagnosis,
      restrictions: restrictionsString,
      recommendations,
      issued_by: assessment.doctor_id,
      doctor_name: assessment.doctor_name,
      doctor_registration_number: null, // not stored in assessment yet
      doctor_signature_url: null,
      pdf_url: null,
      sent_to_employer: false,
      sent_to_patient: false,
      sent_at: null,
      status: 'draft',
      medical_type: medicalType,
      fitness_status: fitnessDecisionToFitnessStatus(assessment.doctor_decision),
      test_results: testResults, // pass through
      // Rules engine data
      rules_evaluation: assessment.rules_engine_summary,
      suggested_fitness_decision: assessment.rules_engine_summary?.overallSuggestedDecision,
      evaluation_confidence: assessment.rules_engine_summary?.overallConfidence,
      doctor_decision_override: assessment.override_rules_engine,
      override_reason: assessment.override_reason,
      // Referral flags
      referrals: referrals as any, // will be stored in settings_override or dedicated field? The Certificate type doesn't have a referrals field; we may need to store in test_results or settings_override. For now we can store in a new field or in settings_override.
      // For simplicity, we'll store in settings_override as referral_flags
    //   settings_override: {
    //     referral_flags: referrals,
    //   },
    };
  }

  private static generateDiagnosis(assessment: ClinicalAssessment): string | undefined {
    const parts: string[] = [];

    if (assessment.clinical_findings?.length) {
      const findingsSummary = assessment.clinical_findings
        .map(f => `${f.category}: ${f.finding} (${f.severity})`)
        .join('; ');
      parts.push(`Clinical findings: ${findingsSummary}`);
    }

    if (assessment.medical_history_notes) {
      parts.push(`Medical history: ${assessment.medical_history_notes}`);
    }

    if (assessment.current_medications) {
      parts.push(`Medications: ${assessment.current_medications}`);
    }

    if (assessment.allergies_confirmed) {
      parts.push(`Allergies: ${assessment.allergies_confirmed}`);
    }

    if (parts.length === 0) {
      return 'No significant findings noted.';
    }
    return parts.join('. ');
  }

  private static generateRecommendations(assessment: ClinicalAssessment): string | undefined {
    const recs: string[] = [];

    if (assessment.follow_up_required) {
      if (assessment.follow_up_date) {
        recs.push(`Follow-up required by ${DateFormatter.formatForDisplay(assessment.follow_up_date)}.`);
      } else {
        recs.push('Follow-up required.');
      }
      if (assessment.follow_up_notes) {
        recs.push(assessment.follow_up_notes);
      }
    }

    if (assessment.referrals?.length) {
      const referralTexts = assessment.referrals.map(r => `${r.type} (${r.priority}): ${r.reason}`);
      recs.push(`Referrals: ${referralTexts.join('; ')}`);
    }

    if (assessment.additional_notes) {
      recs.push(assessment.additional_notes);
    }

    return recs.length ? recs.join(' ') : undefined;
  }

  private static determineMedicalType(assessment: ClinicalAssessment): 'pre_employment' | 'annual' | 'exit' | 'transfer' {
    // Could be determined from appointment_type, but for now default to annual
    return 'annual';
  }
}