"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { FileDown, Loader2, FileText, Table, Download, File } from "lucide-react"
import { toast } from "sonner"
import jsPDF from "jspdf"

type ExportFormat = "pdf" | "csv" | "json"

export function ReportGenerator() {
  const [isGenerating, setIsGenerating] = useState(false)
  const [reportType, setReportType] = useState("clinic-summary")
  const [format, setFormat] = useState<ExportFormat>("pdf")
  const [startDate, setStartDate] = useState(
    new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().split("T")[0],
  )
  const [endDate, setEndDate] = useState(new Date().toISOString().split("T")[0])

  const handleGenerate = async () => {
    setIsGenerating(true)
    try {
      const response = await fetch(`/api/analytics/clinic-report?startDate=${startDate}&endDate=${endDate}`)

      if (!response.ok) {
        throw new Error("Failed to generate report")
      }

      const report = await response.json()

      // Generate based on selected format
      switch (format) {
        case "pdf":
          generatePDF(report, startDate, endDate)
          break
        case "csv":
          generateCSV(report, startDate, endDate)
          break
        case "json":
          generateJSON(report, startDate, endDate)
          break
        default:
          generatePDF(report, startDate, endDate)
      }

      toast.success(`Report generated as ${format.toUpperCase()}`)
    } catch (error) {
      toast.error("Failed to generate report")
      console.error(error)
    } finally {
      setIsGenerating(false)
    }
  }

  const generatePDF = (report: any, startDate: string, endDate: string) => {
    const doc = new jsPDF()
    
    // Add header
    doc.setFontSize(20)
    doc.setTextColor(0, 51, 102) // Dark blue
    doc.text("CLINIC ANALYTICS REPORT", 105, 20, { align: "center" })
    
    // Add date info
    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0) // Black
    doc.text(`Date Range: ${startDate} to ${endDate}`, 20, 40)
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 48)
    doc.text(`Report Type: ${reportType.charAt(0).toUpperCase() + reportType.slice(1)}`, 20, 56)
    
    // Add line separator
    doc.setDrawColor(200, 200, 200)
    doc.line(20, 65, 190, 65)
    
    // APPOINTMENTS SECTION
    doc.setFontSize(16)
    doc.setTextColor(0, 102, 204) // Blue
    doc.text("APPOINTMENTS", 20, 80)
    
    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0)
    doc.text(`Total Appointments: ${report.appointments.total}`, 20, 92)
    doc.text(`Completed: ${report.appointments.completed}`, 20, 100)
    doc.text(`Cancelled: ${report.appointments.cancelled}`, 20, 108)
    doc.text(`No Show: ${report.appointments.noShow}`, 20, 116)
    doc.text(`Completion Rate: ${report.appointments.completionRate.toFixed(2)}%`, 20, 124)
    
    // CERTIFICATES SECTION
    doc.setFontSize(16)
    doc.setTextColor(0, 102, 204)
    doc.text("CERTIFICATES", 20, 145)
    
    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0)
    doc.text(`Total Certificates: ${report.certificates.total}`, 20, 157)
    doc.text(`Fit to Work: ${report.certificates.fitToWork}`, 20, 165)
    doc.text(`Fit with Restrictions: ${report.certificates.fitWithRestrictions}`, 20, 173)
    doc.text(`Unfit to Work: ${report.certificates.unfitToWork}`, 20, 181)
    
    // TEST RESULTS SECTION (if available)
    if (report.testResults) {
      doc.setFontSize(16)
      doc.setTextColor(0, 102, 204)
      doc.text("TEST RESULTS", 20, 200)
      
      doc.setFontSize(12)
      doc.setTextColor(0, 0, 0)
      doc.text(`Total Tests: ${report.testResults.total}`, 20, 212)
      doc.text(`Normal Results: ${report.testResults.normal}`, 20, 220)
      doc.text(`Abnormal Results: ${report.testResults.abnormal}`, 20, 228)
      doc.text(`Normal Rate: ${report.testResults.normalRate.toFixed(2)}%`, 20, 236)
    }
    
    // Add footer
    doc.setFontSize(10)
    doc.setTextColor(128, 128, 128)
    doc.text("Generated by MedSurve Clinic Management System", 105, 280, { align: "center" })
    
    // Save the PDF
    doc.save(`clinic-report-${startDate}-to-${endDate}.pdf`)
  }

  const generateCSV = (report: any, startDate: string, endDate: string) => {
    const csvRows = []
    
    // Header
    csvRows.push(["Clinic Analytics Report"])
    csvRows.push([`Date Range: ${startDate} to ${endDate}`])
    csvRows.push([`Generated: ${new Date().toLocaleDateString()}`])
    csvRows.push([`Report Type: ${reportType}`])
    csvRows.push([])
    
    // APPOINTMENTS
    csvRows.push(["APPOINTMENTS"])
    csvRows.push(["Metric", "Count", "Percentage"])
    csvRows.push(["Total", report.appointments.total, "100%"])
    csvRows.push(["Completed", report.appointments.completed, `${report.appointments.completionRate.toFixed(2)}%`])
    csvRows.push(["Cancelled", report.appointments.cancelled, `${(report.appointments.cancelled / report.appointments.total * 100).toFixed(2)}%`])
    csvRows.push(["No Show", report.appointments.noShow, `${(report.appointments.noShow / report.appointments.total * 100).toFixed(2)}%`])
    csvRows.push([])
    
    // CERTIFICATES
    csvRows.push(["CERTIFICATES"])
    csvRows.push(["Type", "Count", "Percentage"])
    csvRows.push(["Total", report.certificates.total, "100%"])
    csvRows.push(["Fit to Work", report.certificates.fitToWork, `${(report.certificates.fitToWork / report.certificates.total * 100).toFixed(2)}%`])
    csvRows.push(["Fit with Restrictions", report.certificates.fitWithRestrictions, `${(report.certificates.fitWithRestrictions / report.certificates.total * 100).toFixed(2)}%`])
    csvRows.push(["Unfit to Work", report.certificates.unfitToWork, `${(report.certificates.unfitToWork / report.certificates.total * 100).toFixed(2)}%`])
    csvRows.push([])
    
    // TEST RESULTS (if available)
    if (report.testResults) {
      csvRows.push(["TEST RESULTS"])
      csvRows.push(["Metric", "Count", "Percentage"])
      csvRows.push(["Total Tests", report.testResults.total, "100%"])
      csvRows.push(["Normal", report.testResults.normal, `${report.testResults.normalRate.toFixed(2)}%`])
      csvRows.push(["Abnormal", report.testResults.abnormal, `${(report.testResults.abnormal / report.testResults.total * 100).toFixed(2)}%`])
    }
    
    const csvString = csvRows.map(row => row.map(cell => `"${cell}"`).join(",")).join("\n")
    const blob = new Blob([csvString], { type: "text/csv;charset=utf-8;" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `clinic-report-${startDate}-to-${endDate}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  const generateJSON = (report: any, startDate: string, endDate: string) => {
    const enhancedReport = {
      ...report,
      metadata: {
        generatedAt: new Date().toISOString(),
        dateRange: { startDate, endDate },
        reportType,
        format: "json",
      }
    }
    
    const blob = new Blob([JSON.stringify(enhancedReport, null, 2)], { type: "application/json" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `clinic-report-${startDate}-to-${endDate}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  const formatIcons = {
    pdf: FileText,
    csv: Table,
    json: File,
  }

  const formatLabels = {
    pdf: "PDF Document",
    csv: "CSV Spreadsheet",
    json: "JSON Data",
  }

  const FormatIcon = formatIcons[format]

  return (
    <Card>
      <CardHeader>
        <CardTitle>Generate Custom Report</CardTitle>
        <CardDescription>Create detailed reports in multiple formats</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="report-type">Report Type</Label>
          <Select value={reportType} onValueChange={setReportType}>
            <SelectTrigger id="report-type">
              <SelectValue placeholder="Select report type" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="clinic-summary">Clinic Summary</SelectItem>
              <SelectItem value="appointments">Appointments Report</SelectItem>
              <SelectItem value="certificates">Certificates Report</SelectItem>
              <SelectItem value="financial">Financial Report</SelectItem>
              <SelectItem value="test-results">Test Results Report</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <Label htmlFor="format">Export Format</Label>
          <Select value={format} onValueChange={(value: ExportFormat) => setFormat(value)}>
            <SelectTrigger id="format">
              <div className="flex items-center">
                <FormatIcon className="mr-2 h-4 w-4" />
                <SelectValue placeholder="Select format" />
              </div>
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="pdf">
                <div className="flex items-center">
                  <FileText className="mr-2 h-4 w-4" />
                  PDF Document
                </div>
              </SelectItem>
              <SelectItem value="csv">
                <div className="flex items-center">
                  <Table className="mr-2 h-4 w-4" />
                  CSV Spreadsheet
                </div>
              </SelectItem>
              <SelectItem value="json">
                <div className="flex items-center">
                  <File className="mr-2 h-4 w-4" />
                  JSON Data
                </div>
              </SelectItem>
            </SelectContent>
          </Select>
          <p className="text-xs text-muted-foreground">
            {format === "pdf" && "Professional document for printing and sharing"}
            {format === "csv" && "Spreadsheet format compatible with Excel, Google Sheets, etc."}
            {format === "json" && "Structured data for developers and systems"}
          </p>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="start-date">Start Date</Label>
            <Input 
              id="start-date" 
              type="date" 
              value={startDate} 
              onChange={(e) => setStartDate(e.target.value)}
              max={endDate}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="end-date">End Date</Label>
            <Input 
              id="end-date" 
              type="date" 
              value={endDate} 
              onChange={(e) => setEndDate(e.target.value)}
              min={startDate}
              max={new Date().toISOString().split("T")[0]}
            />
          </div>
        </div>

        <div className="rounded-lg border p-4">
          <h4 className="mb-2 text-sm font-medium">Report Preview</h4>
          <div className="space-y-1 text-sm text-muted-foreground">
            <p><span className="font-medium">Type:</span> {reportType.replace("-", " ")}</p>
            <p><span className="font-medium">Format:</span> {formatLabels[format]}</p>
            <p><span className="font-medium">Date Range:</span> {startDate} to {endDate}</p>
            <p><span className="font-medium">File Name:</span> clinic-report-{startDate}-to-{endDate}.{format}</p>
          </div>
        </div>

        <Button 
          onClick={handleGenerate} 
          disabled={isGenerating} 
          className="w-full"
          size="lg"
        >
          {isGenerating ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating {format.toUpperCase()}...
            </>
          ) : (
            <>
              <Download className="mr-2 h-4 w-4" />
              Generate {format.toUpperCase()} Report
            </>
          )}
        </Button>
      </CardContent>
    </Card>
  )
}
